### ISSUE TITLE
The project needs a better readme

### ISSUE THREAD

**Issue by Minion3665** [Goose-Nest/GT-RevertRebrand#15]
The project readme is currently a little lacking, and should probably be expanded or partially rewritten

The following is a list of things that would be good to have in the readme, feel free to expand, remove, or comment below:
- [x] Installation instructions
- [x] Screenshots
- [x] Before and after examples
- [ ] Badges, including version information and further links (such as links to the betterdiscord page for this style or links to another repo such as [this one](https://github.com/MCHSL/classic-discord-css) which reverts even further)

**Comment by CanadaHonk** [comment]
Mostly lacking currently because README.md is automatically generated by GooseThemeBundle - only providing basics inside of it atm.

**Comment by CanadaHonk** [comment]
Mostly done.
