### ISSUE TITLE
Color Errors 

### ISSUE THREAD

**Issue by sv-du** [Goose-Nest/GT-RevertRebrand#16]
I do LOVE how you made this for the community, but there's a few color errors

## Issues
1: Mention colors are a bit "bluer" instead of blurple
2: The "<a> new messages since <time>" bar is blurer then the OG (this honestly could be just me though)
3: Invite People button blurer then OG

## Pictures
# Y = Your Implementation
# O = Original

1.Y = https://i.imgur.com/0saNB0n.png
1.O = https://i.imgur.com/fBFULaL.png

2.Y = https://i.imgur.com/ZiPqZDz.png
2.O = https://i.imgur.com/MuH8OAc.png

3.Y = https://i.imgur.com/h6aWLSX.png
3.O = https://i.imgur.com/R3hJj6K.png

Everything else looks good, it's just that I'm just want everything to be perfect

**Comment by CanadaHonk** [comment]
1. Has mostly been solved by a small tweak.
2. You shouldn't compare with mobile, it's mostly the same color.
3. Fixing soon.

**Comment by sv-du** [comment]
Okay

**Comment by CanadaHonk** [comment]
Most / all have been fixed.
