### ISSUE TITLE
Some elements still have the new colors

### ISSUE THREAD

**Issue by ghost** [Goose-Nest/GT-RevertRebrand#17]
Add friends button still uses new green
https://imgur.com/gvxAwNL.png

Get Nitro button on the emoji popup still uses new green
https://imgur.com/JvXf5nP.png

/ command highlight still uses blue instead of the previous blurple
https://imgur.com/yBOMTqH.png

**Comment by sv-du** [comment]
Oh wow, I thought there was only like 3 color errors, seems like there's 7 tmk

**Comment by Minion3665** [comment]
There's still a number of coloring issues around the app. Thanks for spotting these ones 👍🏼
