### ISSUE TITLE
new discord update broke theme

### ISSUE THREAD

**Issue by sebisonic** [Goose-Nest/GT-RevertRebrand#28]
this theme has been really nice but i think another discord rebranding update broke it and the theme no longer works. ill send some images here:
![image](https://user-images.githubusercontent.com/84886930/119755843-4b0dbd80-be68-11eb-9904-b87c29705158.png)
![image](https://user-images.githubusercontent.com/84886930/119755914-68428c00-be68-11eb-9f98-f6815c8e9d56.png)
![image](https://user-images.githubusercontent.com/84886930/119756004-81e3d380-be68-11eb-9289-dd3fcf823c76.png)
![image](https://user-images.githubusercontent.com/84886930/119756082-a0e26580-be68-11eb-8649-e6ca7fd8a39f.png)

i've restarted my computer, reinstalled betterdiscord and disabled and re-enabled the theme, but there might've been a recent update (not the first rebrand one) which prevented it from activating or something

**Comment by Frosty704** [comment]
same problem

**Comment by CanadaHonk** [comment]
It's because of a big update and it's not been updated on BD's site / store yet. Fixing soon.

**Comment by sebisonic** [comment]
> It's because of a big update and it's not been updated on BD's site / store yet. Fixing soon.

it's fixed for me now 👍
