### ISSUE TITLE
Revert the Discord taskbar icon

### ISSUE THREAD

**Issue by mutageneral** [Goose-Nest/GT-RevertRebrand#31]
I was wondering if we could change the discord icon in the taskbar from this:
![image](https://user-images.githubusercontent.com/62779748/119923894-97c4c780-bf40-11eb-84c0-7a8dc16a0242.png)
To this (not my image): 
![image](https://user-images.githubusercontent.com/62779748/119923914-a57a4d00-bf40-11eb-8475-d036a910b095.png)

 We would not be able to do this with CSS but a plugin could maybe do it? [This plugin](https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/HideIconBadge) is able to change the icon, but I think it just tells discord "there are no notifications, show the no notification icon". 

I guess the only thing I can do now is change the .ico in ``AppData\Local\Discord`` to the original, but I do not have the original. Does anyone, has it?

**Comment by Bl4Cc4t** [comment]
Found the old logo in a subfolder
[app.zip](https://github.com/Goose-Nest/GT-RevertRebrand/files/6566354/app.zip)

**Comment by CanadaHonk** [comment]
Not interested in making a plugin myself but others can, not related to / possible by theme so closing issue.

**Comment by mutageneral** [comment]
> Found the old logo in a subfolder
> [app.zip](https://github.com/Goose-Nest/GT-RevertRebrand/files/6566354/app.zip)

Thank you for this!
