### ISSUE TITLE
[CLOSED] [BetterDiscord] Pfps not showing up properly (+ temp fix)

### ISSUE THREAD

**Issue by m-doescode** [Goose-Nest/GT-RevertRebrand#40]
Profile pictures show up as invisible.

When I open Inspect Element, the url is "goose-nest.github.io/assets/0e291f67c9274a1abdddeb3fd919cbaa.png" rather than "discord.com/assets/0e291f67c9274a1abdddeb3fd919cbaa.png"

In the pfps.css, the url is: "/assets/0e291f67c9274a1abdddeb3fd919cbaa.png"

I can imagine this bug is due to the origin of the pfps.css file being from goose-nest.github.io, so it doesn't work properly.

Does this happen for other people as well? Or is it just on my side.

Temporary fix css:
[pfps.theme.css.zip](https://github.com/Goose-Nest/GT-RevertRebrand/files/6720040/pfps.theme.css.zip)

**Comment by CanadaHonk** [comment]
Yeah I see the issue, will fix in a bit.

**Comment by CanadaHonk** [comment]
(Issue is BD-only afaik.)

**Comment by m-doescode** [comment]
Fixed a while ago by #48
