### ISSUE TITLE
Channel Tags When doing #channelname Print Broken

### ISSUE THREAD

**Issue by DevEvelynn** [Goose-Nest/GT-RevertRebrand#52]
![image](https://user-images.githubusercontent.com/45043402/131221312-bc1dbb51-3b7b-4902-9e25-1d9496e6d0ab.png)

**Comment by CanadaHonk** [comment]
Refresh, already fixed.

**Comment by DevEvelynn** [comment]
how would i refresh using goosemod tho?

**Comment by DaSussy** [comment]
> how would i refresh using goosemod tho?

just restart discord with ctrl+r

**Comment by DevEvelynn** [comment]
Didn't Work The issue still stands

**Comment by DevEvelynn** [comment]
![image](https://user-images.githubusercontent.com/45043402/131243241-2521037c-1903-4387-abc4-2cb10d370fff.png)

**Comment by Kinomora** [comment]
Currently also having this issue with the latest release:
![image](https://user-images.githubusercontent.com/9062578/131767459-5b3017b2-1047-499c-8efa-30f84681d30d.png)
![image](https://user-images.githubusercontent.com/9062578/131767469-37907cb4-f2ce-4152-bb68-45248fef2734.png)

**Comment by Kinomora** [comment]
This seems to be fixed for me using v5.1.
Came here to complain it was still broken but it ended up not being ahaah..
