### ISSUE TITLE
No Longer Changes Discord's Font

### ISSUE THREAD

**Issue by MommyLexie** [Goose-Nest/GT-RevertRebrand#88]
Doesn't seem to change the font anymore

**Comment by KuwuroUsagi** [comment]
Support server clued me in, just added this by going to Settings>Themes, clicking edit on Revert Rebrand, and then putting this a line below the revert windows watermark import:

```
/* Revert font */
@import url('https://css.f53.dev/discord/RevertFont.css'); 
```

**Comment by MommyLexie** [comment]
thanks

**Comment by CanadaHonk** [comment]
Isn't related to rebrand.
